# Generated by Django 4.2.6 on 2023-10-13 07:39

import coinRush.models
import django.contrib.auth.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(blank=True, default='', max_length=255, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('photo_id', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
            managers=[
                ('objects', coinRush.models.AuthUserManager()),
            ],
        ),
    ]
