# Generated by Django 4.2.5 on 2023-11-16 06:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 16, 6, 31, 55, 343445, tzinfo=datetime.timezone.utc)),
        ),
    ]
