# Generated by Django 4.2.5 on 2023-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo_id',
            field=models.ImageField(blank=True, null=True, upload_to='photo_ids/'),
        ),
    ]
