# Generated by Django 4.2.5 on 2023-11-10 21:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0002_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stock_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 21, 54, 8, 487607, tzinfo=datetime.timezone.utc)),
        ),
    ]
