# Generated by Django 4.2.6 on 2023-10-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0002_user_groups_user_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default='2023-10-13 21:33:58'),
        ),
    ]
