# Generated by Django 4.2.5 on 2023-11-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0002_alter_user_password'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
