<<<<<<< HEAD
# Generated by Django 4.2.5 on 2023-11-15 22:41
=======
# Generated by Django 4.2.5 on 2023-11-15 17:21
>>>>>>> 10be4357d42bdf74a39b3ced1cbf5175ea2e9ffa

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('coinRush', '0003_alter_user_created_date'),
=======
        ('coinRush', '0003_user_wallet_alter_user_created_date'),
>>>>>>> 10be4357d42bdf74a39b3ced1cbf5175ea2e9ffa
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 22, 41, 9, 214026, tzinfo=datetime.timezone.utc)),
=======
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 17, 21, 57, 336507, tzinfo=datetime.timezone.utc)),
>>>>>>> 10be4357d42bdf74a39b3ced1cbf5175ea2e9ffa
        ),
    ]
