# Generated by Django 4.2.5 on 2023-11-15 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0003_learn_image_alter_user_created_date'),
        ('coinRush', '0003_user_wallet_alter_user_created_date'),
    ]

    operations = [
    ]
