# Generated by Django 4.2.5 on 2023-11-15 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0003_user_wallet_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 17, 53, 43, 81485, tzinfo=datetime.timezone.utc)),
        ),
    ]
