# Generated by Django 4.2.5 on 2023-11-15 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0004_merge_20231114_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 2, 34, 36, 575582, tzinfo=datetime.timezone.utc)),
        ),
    ]
