# Generated by Django 4.2.5 on 2023-11-17 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0005_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn',
            name='image',
            field=models.ImageField(blank=True, default='topic_images/no-image-available.png', null=True, upload_to='topic_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 17, 2, 56, 29, 283217, tzinfo=datetime.timezone.utc)),
        ),
    ]
