# Generated by Django 4.2.6 on 2023-10-14 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0005_user_is_staff_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 14, 11, 53, 46, 159610, tzinfo=datetime.timezone.utc)),
        ),
    ]
