# Generated by Django 4.2.6 on 2023-10-18 15:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0008_alter_user_created_date_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 18, 15, 38, 19, 310481, tzinfo=datetime.timezone.utc)),
        ),
    ]
