# Generated by Django 4.2.6 on 2023-10-19 01:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0014_learn_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 19, 1, 19, 52, 644121, tzinfo=datetime.timezone.utc)),
        ),
    ]
