# Generated by Django 4.2.6 on 2023-10-27 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0016_coursecategory_alter_learn_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='learn',
            options={'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 27, 2, 10, 18, 929164, tzinfo=datetime.timezone.utc)),
        ),
    ]
