# Generated by Django 4.2.6 on 2023-11-07 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0016_alter_user_created_date_nft_bid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 7, 18, 21, 11, 537265, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
