# Generated by Django 4.2.6 on 2023-11-01 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0019_remove_post_post_comments_alter_user_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 1, 1, 20, 11, 819550, tzinfo=datetime.timezone.utc)),
        ),
    ]
