# Generated by Django 4.2.6 on 2023-11-10 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0020_alter_user_created_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="stock_image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images/"),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 17, 38, 13, 801923, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="userholding",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
