# Generated by Django 4.2.6 on 2023-11-10 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0021_stock_stock_image_alter_transaction_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="stock_image",
            field=models.ImageField(blank=True, null=True, upload_to="new_images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 17, 53, 49, 466757, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
