# Generated by Django 4.2.5 on 2023-11-09 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0021_alter_user_created_date'),
        ('coinRush', '0021_alter_user_created_date_newscomments'),
    ]

    operations = [
    ]
