# Generated by Django 4.2.5 on 2023-11-09 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0021_alter_user_created_date_newscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 53, 13, 895645, tzinfo=datetime.timezone.utc)),
        ),
    ]
