# Generated by Django 4.2.5 on 2023-11-09 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0022_merge_20231109_1734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learn',
            name='external_link',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 9, 22, 34, 39, 17807, tzinfo=datetime.timezone.utc)),
        ),
    ]
