# Generated by Django 4.2.5 on 2023-11-10 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0021_alter_user_created_date_alter_user_profile_pic'),
        ('coinRush', '0023_alter_transaction_quantity_alter_user_created_date_and_more'),
    ]

    operations = [
    ]
