# Generated by Django 4.2.6 on 2023-11-10 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0023_alter_stock_stock_image_alter_user_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 17, 58, 39, 588307, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
