# Generated by Django 4.2.5 on 2023-11-10 02:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0023_remove_learn_external_link_alter_user_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 10, 2, 8, 58, 808890, tzinfo=datetime.timezone.utc)),
        ),
    ]
