# Generated by Django 4.2.6 on 2023-11-11 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinRush', '0024_news_likes_user_liked_news_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cover_image',
            field=models.ImageField(blank=True, default='news_covers/placeholder.png', null=True, upload_to='news_covers/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 11, 17, 54, 34, 678692, tzinfo=datetime.timezone.utc)),
        ),
    ]
