# Generated by Django 4.2.6 on 2023-11-10 18:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0027_alter_user_created_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="stock_image",
        ),
        migrations.AddField(
            model_name="stock",
            name="coin_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="coinRush/static/images/"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 18, 10, 27, 147618, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
