# Generated by Django 4.2.6 on 2023-11-10 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0028_remove_stock_stock_image_stock_coin_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="coin_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 18, 11, 32, 476008, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
