# Generated by Django 4.2.6 on 2023-11-10 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0035_alter_user_created_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 18, 22, 27, 578035, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
