# Generated by Django 4.2.6 on 2023-11-10 19:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "coinRush",
            "0023_alter_transaction_quantity_alter_user_created_date_and_more",
        ),
        ("coinRush", "0040_alter_stock_coin_image_alter_user_created_date"),
    ]

    operations = []
