# Generated by Django 4.2.6 on 2023-11-10 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0041_merge_20231110_1429"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stock",
            old_name="coin_image",
            new_name="image",
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 19, 33, 58, 526481, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
