# Generated by Django 4.2.6 on 2023-11-10 19:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("coinRush", "0042_rename_coin_image_stock_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 10, 19, 35, 30, 769427, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
